### ISSUE TITLE
joint_trajectory_controller: Gets a segmentation fault after many calls

### ISSUE THREAD

**Issue by jim-rothrock** [ros-controls/ros_controllers#60]
I'm using FollowJointTrajectoryAction to control a robot arm when I'm teleoperating it with a joystick. Goals contain a single waypoint, and are sent at a maximum rate of 30 Hz. After about two minutes (~3600 goals sent), a segmentation fault occurs in the joint trajectory controller. This happens even when all the goals are identical. I've tried sending goals only when the positions in the goal change, but that just postpones the segmentation fault. I'm using the joint trajectory controller from hydro-devel, cloned on 10/31/13.

The segmentation fault message:

```
Segmentation fault (core dumped)
[cerberus/gazebo-4] process has died [pid 5321, exit code 139, cmd /mnt/nvx/jim/catkin_ws/src/gazebo_ros_pkgs/gazebo_ros/scripts/gzserver /mnt/nvx/jim/catkin_ws/src/cerberus/cerberus_gazebo/worlds/srrc_course.sdf __name:=gazebo __log:=/home/jimr/.ros/log/c9dc7342-4326-11e3-b73f-c8600024ec42/cerberus-gazebo-4.log].
log file: /home/jimr/.ros/log/c9dc7342-4326-11e3-b73f-c8600024ec42/cerberus-gazebo-4*.log
```

The beginning of the stack trace:

```
Core was generated by `gzserver /mnt/nvx/jim/catkin_ws/src/cerberus/cerberus_gazebo/worlds/srrc_course'.
Program terminated with signal 11, Segmentation fault.
#0  0x000000000042de66 in boost::detail::shared_count::~shared_count() ()
(gdb) where
#0  0x000000000042de66 in boost::detail::shared_count::~shared_count() ()
#1  0x00007fdbc0fbdcea in boost::shared_ptr<realtime_tools::RealtimeServerGoalHandle<control_msgs::FollowJointTrajectoryAction_<std::allocator<void> > > >::~shared_ptr (this=0x7fdbc37fd720, __in_chrg=<optimized out>)
    at /usr/include/boost/smart_ptr/shared_ptr.hpp:168
#2  0x00007fdbc0fc16fb in joint_trajectory_controller::JointTrajectoryController<trajectory_interface::QuinticSplineSegment<double>, hardware_interface::PositionJointInterface>::update (this=0x7fdbec0133a0, time=..., period=...)
    at /mnt/nvx/jim/catkin_ws/src/ros_controllers/joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller_impl.h:424
#3  0x00007fdbc1f2815f in controller_interface::ControllerBase::updateRequest (
    this=0x7fdbec0133a0, time=..., period=...)
    at /mnt/nvx/jim/catkin_ws/src/ros_control/controller_interface/include/controller_interface/controller_base.h:91
#4  0x00007fdbc1f206a0 in controller_manager::ControllerManager::update (
    this=0x7fdbb4023080, time=..., period=..., reset_controllers=false)
    at /mnt/nvx/jim/catkin_ws/src/ros_control/controller_manager/src/controller_manager.cpp:92
#5  0x00007fdbe0398b7c in gazebo_ros_control::GazeboRosControlPlugin::Update (
    this=0x7fdbb40ed7e0)
    at /mnt/nvx/jim/catkin_ws/src/gazebo_ros_pkgs/gazebo_ros_control/src/gazebo_ros_control_plugin.cpp:210
```

Here is a program that demonstrates the problem. Replace "cerberus", the controller name, and the joint names with values that will work with your robot. I'm using a Gazebo simulation of Cerberus.

```
#!/usr/bin/env python

"""joint_traj_test.py"""

import actionlib
import rospy

from control_msgs.msg import FollowJointTrajectoryAction
from control_msgs.msg import FollowJointTrajectoryGoal
from controller_manager_msgs.srv import ListControllers
from trajectory_msgs.msg import JointTrajectory
from trajectory_msgs.msg import JointTrajectoryPoint


def _wait_for_ctrlr(list_ctrlrs, ctrlr_name):
    while True:
        response = list_ctrlrs()
        for ctrlr in response.controller:
            if ctrlr.name == ctrlr_name:
                if ctrlr.state == "running":
                    return
                rospy.sleep(0.1)
                break


rospy.init_node("joint_traj_test")

# Wait for the joint trajectory controller to be in the "running" state.
list_ctrlrs = rospy.ServiceProxy("/cerberus/controller_manager/"
                                 "list_controllers",   ListControllers)
list_ctrlrs.wait_for_service()
_wait_for_ctrlr(list_ctrlrs, "arm_ctrlr")

client = actionlib.SimpleActionClient("/cerberus/arm_ctrlr/"
                                      "follow_joint_trajectory",
                                      FollowJointTrajectoryAction)
client.wait_for_server()

traj_point = JointTrajectoryPoint(positions=[0.0, 1.0, 0.0],
                                  velocities=[0.0] * 3,
                                  accelerations=[0.0] * 3,
                                  effort=[0.0] * 3,
                                  time_from_start=rospy.Duration(1 / 30.0))
traj = JointTrajectory(joint_names=("arm_base_joint", "shoulder_joint",
                                    "elbow_joint"), points=[traj_point])
goal = FollowJointTrajectoryGoal(trajectory=traj)

while not rospy.is_shutdown():
    goal.trajectory.header.stamp = rospy.get_rostime()
    client.send_goal(goal)
    client.wait_for_result()
    rospy.sleep(1 / 30.0)
```

**Comment by adolfo-rt** [comment]
Hi Jim, thanks for reporting and providing an example on how to reproduce. I'll try to add a regression test along with the fix to make sure the issue does not reappear in future code refactors.

It can be a few weeks before I can find a slot to fix the issue. How blocking is this for you?.

**Comment by jim-rothrock** [comment]
> It can be a few weeks before I can find a slot to fix the issue. How blocking is this for you?.

It won't block me until the beginning of December.

**Comment by adolfo-rt** [comment]
I'll try to have a fix by then. No promises, though. Tight schedule these weeks.

**Comment by adolfo-rt** [comment]
I already started to look into this. I've managed to reproduce the problem and already have some patch proposals. I'd still like to spend some more time testing to make sure that all is in order. So far I've reached 3.5 days of uninterrupted use with no crashes.

**Comment by jim-rothrock** [comment]
Thanks for taking a look at this!

**Comment by adolfo-rt** [comment]
@jim-rothrock: Please give hydro-devel a try now that I've merged the fix. It should now work as expected.

**Comment by jim-rothrock** [comment]
Thanks for fixing it! I've tested the changes, and the problem is now gone. I'm closing this issue.

**Comment by adolfo-rt** [comment]
And thank you for helping us harden the implementation :-)

**Comment by jacknlliu** [comment]
Hi, I got the following error using joint trajectory controller and gazebo,

```
[ERROR] [1517823475.098197028, 20202.025000000]: To transition to a cancelled state, the goal must be in a pending, recalling, active, or preempting state, it is currently in state: 2

Segmentation fault (core dumped)

[gazebo-1] process has died [pid 1072, exit code 139, cmd /opt/ros/kinetic/lib/gazebo_ros/gzserver -e ode /data/assembler/assembler-dynamic/src/assembler_description/world/myworkcell-with-base-fix-physics.world __name:=gazebo __log:=/home/ros/.ros/log/93541f82-0a23-11e8-aa83-06d51cc02108/gazebo-1.log].
log file: /home/ros/.ros/log/93541f82-0a23-11e8-aa83-06d51cc02108/gazebo-1*.log
```
Is this related with joint trajectory controller?
